name: Generate and upload test coverage report to codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install coverage
        pip install -r requirements.txt
        pip install .
        coverage run -m pytest test
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
